### ISSUE TITLE
Spdlog

### ISSUE THREAD

**Issue by ayalma** [Krysl/keyboard_event#1]
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at flutter/ephemeral/.plugin_symlinks/keyboard_event/windows/CMakeLists.txt:26 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been

**Comment by holai** [comment]
I also encountered this problem, may I ask if you have a solution

**Comment by universalbugreporter** [comment]
Very useful package.  Right now it is showing this error at Windows 10. Not running the application from Android Studio showing same error message related to spdlog and cmake file. 
Please fix this issue.
