### ISSUE TITLE
LMENU + any Key doesn't capture KeyUp Event for the other key

### ISSUE THREAD

**Issue by mulaRahul** [Krysl/keyboard_event#3]
I'm listening to the **KeyDown** and **KeyUp** events (`KeyEvent.isKeyDown` and `KeyEvent.isKeyUp`). When pressing the `LMENU` (Left Alt) Key, along with any other key like `LMENU` + `U`, the KeyDown events for both of them are captured. But when the keys are released, only `LMENU`'s KeyUp event is captured (_the same can be seen in the attached video_).

Specs:
- Flutter 3.0.2
- Platform: Windows
- keyboard_event 0.3.2

https://user-images.githubusercontent.com/96373135/174606124-176401be-0c51-4a21-908a-7d7f199ac2b3.mp4

**Comment by Krysl** [comment]
[KBDLLHOOKSTRUCT structure (winuser.h)
](https://docs.microsoft.com/en-US/windows/win32/api/winuser/ns-winuser-kbdllhookstruct)
```c
typedef struct tagKBDLLHOOKSTRUCT {
  DWORD     vkCode;
  DWORD     scanCode;
  DWORD     flags;
  DWORD     time;
  ULONG_PTR dwExtraInfo;
} KBDLLHOOKSTRUCT, *LPKBDLLHOOKSTRUCT, *PKBDLLHOOKSTRUCT;
```
flags Type: DWORD
|Value | Meaning |
|---|---|
| LLKHF_UP <br/>   (KF_UP >> 8)  | Test the transition-state flag.|

It seems that this bit needs to be checked additionally.

**Comment by mulaRahul** [comment]
Great! Checking the `flags` was needed after all. Also thanks for your work, the package really made it easier to get Low-Level Keyboard events! (I'll attach a preview of what I'm building)

Cheers 🍻!

https://user-images.githubusercontent.com/96373135/174725330-aa15e7e8-f845-436d-a1f3-768f34d95eb5.mp4
