### ISSUE TITLE
timestamp.h error C2220

### ISSUE THREAD

**Issue by hengheng1220** [Krysl/keyboard_event#4]
你好，示例代码运行报错，获取时间那个显示中文了，是不是编码过不去了？需要怎么设置下呢

**Comment by hengheng1220** [comment]
![image](https://user-images.githubusercontent.com/7610728/177067558-d71d1174-40cd-4bb8-b53b-7f115228849d.png)

**Comment by Krysl** [comment]
我在 `CMakeLists.txt` 里加了对 utf8 的处理(如下)，所以插件相关的代码都应是`utf-8`的，但你的错误好像是cmake生成的`timestamp.h`被存为了`gbk`，有些奇怪，不知道是cmake的版本不太对还是怎么的。
https://github.com/Krysl/keyboard_event/blob/8064b281fe31f5b5fc6a827a3190d2106210113e/windows/CMakeLists.txt#L115

或许可以试试把下面那行改成 `COMMAND cmd /C chcp 65001 && timestamp.bat .` 
https://github.com/Krysl/keyboard_event/blob/8064b281fe31f5b5fc6a827a3190d2106210113e/windows/CMakeLists.txt#L111

我这边如果把 65001 改成 936，就会出现跟你一样的错误：
<img width="824" alt="timestamp bug" src="https://user-images.githubusercontent.com/5905801/177150802-1a7ec004-68d9-41cc-b027-db59f711a802.png">

(如果可能的话，希望提供`flutter build windows -v`的详细打印信息)。

---

实在不行的话，完全可以把时间戳相关的代码都去掉，毕竟也不是什么非要不可的功能。

**Comment by Krysl** [comment]
也有可能是因为我不知道什么时候设置过下面的注册表项了(改为65001就编译成功，而改为936就出错)

> 1. win+R 输入regedit 进入注册表 
> 2. 找到 `HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe` 
> 如果该项下已存在CodePage项，则把值改为十进制”65001”；
> 如果不存在，在该项下新建一个 DWORD（32位值），命名为“CodePage”，值设为“65001” 
> 3. 重启cmd后生效

**Comment by hengheng1220** [comment]
> 我在 `CMakeLists.txt` 里加了对 utf8 的处理(如下)，所以插件相关的代码都应是`utf-8`的，但你的错误好像是cmake生成的`timestamp.h`被存为了`gbk`，有些奇怪，不知道是cmake的版本不太对还是怎么的。
> 
> https://github.com/Krysl/keyboard_event/blob/8064b281fe31f5b5fc6a827a3190d2106210113e/windows/CMakeLists.txt#L115
> 
> 或许可以试试把下面那行改成 `COMMAND cmd /C chcp 65001 && timestamp.bat .`
> 
> https://github.com/Krysl/keyboard_event/blob/8064b281fe31f5b5fc6a827a3190d2106210113e/windows/CMakeLists.txt#L111
> 
> 我这边如果把 65001 改成 936，就会出现跟你一样的错误： <img alt="timestamp bug" width="824" src="https://user-images.githubusercontent.com/5905801/177150802-1a7ec004-68d9-41cc-b027-db59f711a802.png">
> 
> (如果可能的话，希望提供`flutter build windows -v`的详细打印信息)。
> 
> 实在不行的话，完全可以把时间戳相关的代码都去掉，毕竟也不是什么非要不可的功能。

这样修改可以了，感谢

**Comment by cike8899** [comment]
改成`COMMAND cmd /C chcp 65001 && timestamp.bat .`有效，考虑发一版吗？ @Krysl

**Comment by Krysl** [comment]
@cike8899 发了

**Comment by cike8899** [comment]
> @cike8899 发了

谢谢大佬
